GLOBAL_LIST_EMPTY(cable_list)
GLOBAL_LIST_EMPTY(airlocks)
GLOBAL_LIST_EMPTY(machines)
GLOBAL_LIST_EMPTY(syndicate_shuttle_boards)

GLOBAL_LIST(chemical_reactions_list)
GLOBAL_LIST(chemical_reagents_list)	
GLOBAL_LIST_EMPTY(materials_list)
GLOBAL_LIST_EMPTY(rcd_list)
GLOBAL_LIST_EMPTY(apcs_list)
GLOBAL_LIST_EMPTY(poi_list)
GLOBAL_LIST_EMPTY(pinpointer_list)

GLOBAL_LIST_EMPTY(wire_color_directory)
GLOBAL_LIST_EMPTY(wire_name_directory)