#define MOLES			1
#define ARCHIVE			2
#define GAS_META		3
#define META_GAS_SPECIFIC_HEAT	1
#define META_GAS_NAME			2
#define META_GAS_MOLES_VISIBLE	3
#define META_GAS_OVERLAY		4
#define META_GAS_DANGER			5
#define META_GAS_ID				6
#define META_GAS_FUSION_POWER   7

#define R_IDEAL_GAS_EQUATION	8.31
#define ONE_ATMOSPHERE			101.325
#define TCMB					2.7
#define TCRYO					225
#define T0C						273.15
#define T20C					293.15

#define MOLES_CELLSTANDARD		(ONE_ATMOSPHERE*CELL_VOLUME/(T20C*R_IDEAL_GAS_EQUATION))
#define M_CELL_WITH_RATIO		(MOLES_CELLSTANDARD * 0.005)
#define O2STANDARD				0.21
#define N2STANDARD				0.79
#define CELL_VOLUME				2500

#define EXCITED_GROUP_BREAKDOWN_CYCLES				4
#define EXCITED_GROUP_DISMANTLE_CYCLES				16
#define MINIMUM_AIR_RATIO_TO_SUSPEND				0.1
#define MINIMUM_AIR_RATIO_TO_MOVE					0.001
#define MINIMUM_AIR_TO_SUSPEND						(MOLES_CELLSTANDARD*MINIMUM_AIR_RATIO_TO_SUSPEND)
#define MINIMUM_MOLES_DELTA_TO_MOVE					(MOLES_CELLSTANDARD*MINIMUM_AIR_RATIO_TO_MOVE)
#define MINIMUM_TEMPERATURE_TO_MOVE					(T20C+100)
#define MINIMUM_TEMPERATURE_DELTA_TO_SUSPEND		4
#define MINIMUM_TEMPERATURE_DELTA_TO_CONSIDER		0.5
#define MINIMUM_TEMPERATURE_FOR_SUPERCONDUCTION		(T20C+10)
#define MINIMUM_TEMPERATURE_START_SUPERCONDUCTION	(T20C+200)

#define WALL_HEAT_TRANSFER_COEFFICIENT		0.0
#define OPEN_HEAT_TRANSFER_COEFFICIENT		0.4
#define WINDOW_HEAT_TRANSFER_COEFFICIENT	0.1	
#define HEAT_CAPACITY_VACUUM				7000

#define MIN_TOXIC_GAS_DAMAGE				1
#define MAX_TOXIC_GAS_DAMAGE				10
#define MOLES_GAS_VISIBLE					0.25

#define FIRE_MINIMUM_TEMPERATURE_TO_SPREAD	(150+T0C)
#define FIRE_MINIMUM_TEMPERATURE_TO_EXIST	(100+T0C)
#define FIRE_SPREAD_RADIOSITY_SCALE			0.85
#define FIRE_GROWTH_RATE					40000
#define PLASMA_MINIMUM_BURN_TEMPERATURE		(100+T0C)
#define PLASMA_UPPER_TEMPERATURE			(1370+T0C)
#define PLASMA_OXYGEN_FULLBURN				10

#define FACTOR_GAS_VISIBLE_MAX				20
#define MOLES_GAS_VISIBLE_STEP				0.25

#define HAZARD_HIGH_PRESSURE				550
#define WARNING_HIGH_PRESSURE				325
#define WARNING_LOW_PRESSURE				50
#define HAZARD_LOW_PRESSURE					20

#define BODYTEMP_NORMAL						310.15
#define BODYTEMP_AUTORECOVERY_DIVISOR		11
#define BODYTEMP_AUTORECOVERY_MINIMUM		12
#define BODYTEMP_COLD_DIVISOR				6
#define BODYTEMP_HEAT_DIVISOR				15
#define BODYTEMP_COOLING_MAX				-100
#define BODYTEMP_HEATING_MAX				30

#define SPACE_HELM_MIN_TEMP_PROTECT			2.0
#define SPACE_HELM_MAX_TEMP_PROTECT			1500
#define SPACE_SUIT_MIN_TEMP_PROTECT			2.0
#define SPACE_SUIT_MAX_TEMP_PROTECT			1500

#define FIRE_SUIT_MIN_TEMP_PROTECT			60
#define FIRE_SUIT_MAX_TEMP_PROTECT			30000
#define FIRE_HELM_MIN_TEMP_PROTECT			60
#define FIRE_HELM_MAX_TEMP_PROTECT			30000

#define FIRE_IMMUNITY_MAX_TEMP_PROTECT	35000

#define HELMET_MIN_TEMP_PROTECT				160
#define HELMET_MAX_TEMP_PROTECT				600
#define ARMOR_MIN_TEMP_PROTECT				160
#define ARMOR_MAX_TEMP_PROTECT				600

#define GLOVES_MIN_TEMP_PROTECT				2.0
#define GLOVES_MAX_TEMP_PROTECT				1500
#define SHOES_MIN_TEMP_PROTECT				2.0
#define SHOES_MAX_TEMP_PROTECT				1500

#define MAX_OUTPUT_PRESSURE					4500
#define MAX_TRANSFER_RATE					200

#define UNARY		1
#define BINARY 		2
#define TRINARY		3
#define QUATERNARY	4

#define TANK_MELT_TEMPERATURE				1000000
#define TANK_LEAK_PRESSURE					(30.*ONE_ATMOSPHERE)
#define TANK_RUPTURE_PRESSURE				(35.*ONE_ATMOSPHERE)
#define TANK_FRAGMENT_PRESSURE				(40.*ONE_ATMOSPHERE)
#define TANK_FRAGMENT_SCALE	    			(6.*ONE_ATMOSPHERE)
#define TANK_MAX_RELEASE_PRESSURE 			(ONE_ATMOSPHERE*3)
#define TANK_MIN_RELEASE_PRESSURE 			0
#define TANK_DEFAULT_RELEASE_PRESSURE 		16

#define ATMOS_PASS_YES 1
#define ATMOS_PASS_NO 0
#define ATMOS_PASS_PROC -1
#define ATMOS_PASS_DENSITY -2

#define ATMOS_TANK_N2O				"n2o=6000;TEMP=293.15"
#define ATMOS_TANK_CO2				"co2=50000;TEMP=293.15"
#define ATMOS_TANK_PLASMA			"plasma=70000;TEMP=293.15"
#define ATMOS_TANK_O2				"o2=100000;TEMP=293.15"
#define ATMOS_TANK_N2				"n2=100000;TEMP=293.15"
#define ATMOS_TANK_AIRMIX			"o2=2644;n2=10580;TEMP=293.15"

#define LAVALAND_DEFAULT_ATMOS "o2=14;n2=23;TEMP=300"

#define ATMOS_GAS_MONITOR_INPUT_O2 "o2_in"
#define ATMOS_GAS_MONITOR_OUTPUT_O2 "o2_out"
#define ATMOS_GAS_MONITOR_SENSOR_O2 "o2_sensor"

#define ATMOS_GAS_MONITOR_INPUT_TOX "tox_in"
#define ATMOS_GAS_MONITOR_OUTPUT_TOX "tox_out"
#define ATMOS_GAS_MONITOR_SENSOR_TOX "tox_sensor"

#define ATMOS_GAS_MONITOR_INPUT_AIR "air_in"
#define ATMOS_GAS_MONITOR_OUTPUT_AIR "air_out"
#define ATMOS_GAS_MONITOR_SENSOR_AIR "air_sensor"

#define ATMOS_GAS_MONITOR_INPUT_MIX "mix_in"
#define ATMOS_GAS_MONITOR_OUTPUT_MIX "mix_out"
#define ATMOS_GAS_MONITOR_SENSOR_MIX "mix_sensor"

#define ATMOS_GAS_MONITOR_INPUT_N2O "n2o_in"
#define ATMOS_GAS_MONITOR_OUTPUT_N2O "n2o_out"
#define ATMOS_GAS_MONITOR_SENSOR_N2O "n2o_sensor"

#define ATMOS_GAS_MONITOR_INPUT_N2 "n2_in"
#define ATMOS_GAS_MONITOR_OUTPUT_N2 "n2_out"
#define ATMOS_GAS_MONITOR_SENSOR_N2 "n2_sensor"

#define ATMOS_GAS_MONITOR_INPUT_CO2 "co2_in"
#define ATMOS_GAS_MONITOR_OUTPUT_CO2 "co2_out"
#define ATMOS_GAS_MONITOR_SENSOR_CO2 "co2_sensor"

#define ATMOS_GAS_MONITOR_INPUT_INCINERATOR "incinerator_in"
#define ATMOS_GAS_MONITOR_OUTPUT_INCINERATOR "incinerator_out"
#define ATMOS_GAS_MONITOR_SENSOR_INCINERATOR "incinerator_sensor"

#define ATMOS_GAS_MONITOR_INPUT_TOXINS_LAB "toxinslab_in"
#define ATMOS_GAS_MONITOR_OUTPUT_TOXINS_LAB "toxinslab_out"
#define ATMOS_GAS_MONITOR_SENSOR_TOXINS_LAB "toxinslab_sensor"

#define ATMOS_GAS_MONITOR_LOOP_DISTRIBUTION "distro-loop_meter"
#define ATMOS_GAS_MONITOR_LOOP_ATMOS_WASTE "atmos-waste_loop_meter"

#define ATMOS_GAS_MONITOR_WASTE_ENGINE "engine-waste_out"
#define ATMOS_GAS_MONITOR_WASTE_ATMOS "atmos-waste_out"

#define CANATMOSPASS(A, O) ( A.CanAtmosPass == ATMOS_PASS_PROC ? A.CanAtmosPass(O) : ( A.CanAtmosPass == ATMOS_PASS_DENSITY ? !A.density : A.CanAtmosPass ) )
#define CANVERTICALATMOSPASS(A, O) ( A.CanAtmosPassVertical == ATMOS_PASS_PROC ? A.CanAtmosPass(O, TRUE) : ( A.CanAtmosPassVertical == ATMOS_PASS_DENSITY ? !A.density : A.CanAtmosPassVertical ) )

#define OPENTURF_DEFAULT_ATMOS		"o2=22;n2=82;TEMP=293.15"
#define TCOMMS_ATMOS				"n2=100;TEMP=80"
#define AIRLESS_ATMOS				"TEMP=2.7"
#define FROZEN_ATMOS				"o2=22;n2=82;TEMP=180"
#define KITCHEN_COLDROOM_ATMOS		"o2=33;n2=124;TEMP=193.15"
#define BURNMIX_ATMOS				"o2=2500;plasma=5000;TEMP=370"

#define PIPING_LAYER_MIN 1
#define PIPING_LAYER_MAX 3
#define PIPING_LAYER_DEFAULT 2
#define PIPING_LAYER_P_X 5
#define PIPING_LAYER_P_Y 5
#define PIPING_LAYER_LCHANGE 0.05

#define PIPING_ALL_LAYER				(1<<0)
#define PIPING_ONE_PER_TURF				(1<<1)
#define PIPING_DEFAULT_LAYER_ONLY		(1<<2)
#define PIPING_CARDINAL_AUTONORMALIZE	(1<<3)

#define PIPING_LAYER_SHIFT(T, PipingLayer) \
	if(T.dir & (NORTH|SOUTH)) {									\
		T.pixel_x = (PipingLayer - PIPING_LAYER_DEFAULT) * PIPING_LAYER_P_X;\
	}																		\
	if(T.dir & (EAST|WEST)) {										\
		T.pixel_y = (PipingLayer - PIPING_LAYER_DEFAULT) * PIPING_LAYER_P_Y;\
	}

#define PIPING_LAYER_DOUBLE_SHIFT(T, PipingLayer) \
	T.pixel_x = (PipingLayer - PIPING_LAYER_DEFAULT) * PIPING_LAYER_P_X;\
	T.pixel_y = (PipingLayer - PIPING_LAYER_DEFAULT) * PIPING_LAYER_P_Y;

#define THERMAL_ENERGY(gas) (gas.temperature * gas.heat_capacity())

#define ADD_GAS(gas_id, out_list)\
	var/list/tmp_gaslist = GLOB.gaslist_cache[gas_id]; out_list[gas_id] = tmp_gaslist.Copy();

#define ASSERT_GAS(gas_id, gas_mixture) if (!gas_mixture.gases[gas_id]) { ADD_GAS(gas_id, gas_mixture.gases) };

#define TOTAL_MOLES(cached_gases, out_var)\
	out_var = 0;\
	for(var/total_moles_id in cached_gases){\
		out_var += cached_gases[total_moles_id][MOLES];\
	}