#define CLEAN_WEAK 			2
#define CLEAN_MEDIUM		3
#define CLEAN_STRONG		4
#define CLEAN_IMPRESSIVE	5
#define CLEAN_GOD			6

#define CLEAN_STRENGTH_FINGERPRINTS CLEAN_IMPRESSIVE
#define CLEAN_STRENGTH_BLOOD CLEAN_WEAK
#define CLEAN_STRENGTH_FIBERS CLEAN_IMPRESSIVE